### ISSUE TITLE
Stock Information - Limited Data

### ISSUE THREAD

**Issue by stevenaquinn** [esea48/MoelisIR#10]
On the Stock Information page, there is just barely over 2 years of data, making the difference between a 2 year and a 3 year chart negligible, there is no difference between a 3yr and 5yr chart and Custom date ranges can produce a mostly empty chart.

![stock_information_chart_data](https://cloud.githubusercontent.com/assets/18052292/14888982/c87327e6-0d2a-11e6-9abf-2492c5747ee1.gif)

**Comment by stevenaquinn** [comment]
Doesn't appear to be any more data in the data set at this point, meaning the 2Y & 3Y charts only have an extra month of data in them and the 3Y and 5Y are the same.  Custom ranges have been improved, it will not let you select anything outside of what is available in the data set (it will let you try other dates, but will force start date back to 4/15/14). @esea48 Are we planning on adding the legacy data? If not we should remove the 3Y & 5Y chart options.

**Comment by DharmeshRana** [comment]
Please see below press release. As per PR, Moelis started trading on April 16, 2014.
http://investors.moelis.com/file.aspx?IID=4363272&FID=23216266

I would recommend to keep 3Y and 5Y since this would be design hard code and if we miss to activate this options in future, it would be a risk. I am sure investors know when Moelis started trading. I see same options are available on the current IR site as well.
