### ISSUE TITLE
Chart edits - Stock Info

### ISSUE THREAD

**Issue by esea48** [esea48/MoelisIR#42]
- [ ]  In the key, “MC” should be “Price” 
- [ ]  Charts—overlays.  When checking any box in the dropdown, they don’t work.
- [ ] Charts-missing “Add Comparison Tickers” language above chart on far right next to plus sign

![screen shot 2016-05-16 at 1 53 28 pm](https://cloud.githubusercontent.com/assets/10871398/15298458/5f7f2004-1b6d-11e6-93e3-f8660b0de877.png)

**Comment by esea48** [comment]
@DharmeshRana - is this doable?

**Comment by DharmeshRana** [comment]
Below is still R&D and our design team is looking into this. As mentioned since this is within chart frame, it would be hard to fix.
1) In the key, “MC” should be “Price”

This has been fixed.
2) Charts—overlays. When checking any box in the dropdown, they don’t work.

We are not able to replicate this. If you can, please forward me screenshot.
Charts-missing “Add Comparison Tickers” language above chart on far right next to plus sign

**Comment by DharmeshRana** [comment]
"MC" is showing as "Price" now on the chart.
